import js from '@eslint/js'
import globals from 'globals'
import pluginVue from 'eslint-plugin-vue'
import vueA11y from 'eslint-plugin-vuejs-accessibility'
import tsParser from '@typescript-eslint/parser'
import vueParser from 'vue-eslint-parser'

/** Nuxt / Vue auto-imports used across app + server. */
const nuxtGlobals = {
  // Vue
  computed: 'readonly',
  ref: 'readonly',
  reactive: 'readonly',
  watch: 'readonly',
  watchEffect: 'readonly',
  onMounted: 'readonly',
  onBeforeUnmount: 'readonly',
  onUnmounted: 'readonly',
  nextTick: 'readonly',
  defineProps: 'readonly',
  defineEmits: 'readonly',
  defineExpose: 'readonly',
  withDefaults: 'readonly',
  // Nuxt
  definePageMeta: 'readonly',
  defineNuxtPlugin: 'readonly',
  defineNuxtRouteMiddleware: 'readonly',
  defineEventHandler: 'readonly',
  defineNitroPlugin: 'readonly',
  navigateTo: 'readonly',
  useRouter: 'readonly',
  useRoute: 'readonly',
  useState: 'readonly',
  useCookie: 'readonly',
  useFetch: 'readonly',
  useAsyncData: 'readonly',
  useLazyFetch: 'readonly',
  useLazyAsyncData: 'readonly',
  useRequestURL: 'readonly',
  useRequestHeaders: 'readonly',
  useRuntimeConfig: 'readonly',
  useNuxtApp: 'readonly',
  useHead: 'readonly',
  useSeoMeta: 'readonly',
  createError: 'readonly',
  showError: 'readonly',
  clearError: 'readonly',
  // h3 / nitro
  getQuery: 'readonly',
  getRouterParam: 'readonly',
  getHeader: 'readonly',
  getHeaders: 'readonly',
  setHeader: 'readonly',
  setCookie: 'readonly',
  getCookie: 'readonly',
  readBody: 'readonly',
  getRequestIP: 'readonly',
  sendRedirect: 'readonly',
  // auth / i18n / prisma (project auto-imports)
  useUserSession: 'readonly',
  setUserSession: 'readonly',
  clearUserSession: 'readonly',
  requireUserSession: 'readonly',
  useI18n: 'readonly',
  useLocalePath: 'readonly',
  useSwitchLocalePath: 'readonly',
  prisma: 'readonly',
  useAdminSecret: 'readonly',
  useAuth: 'readonly',
  useAuthFlow: 'readonly',
  useAuthedFetch: 'readonly',
  useBookingLabels: 'readonly',
  useCheckout: 'readonly',
  useClubFavorites: 'readonly',
  useCourtBooking: 'readonly',
  useFetchError: 'readonly',
  useFormatters: 'readonly',
  useGoogleAuth: 'readonly',
  useImageUpload: 'readonly',
  useLocalDate: 'readonly',
  useLocalizedField: 'readonly',
  useOwnerClubRefresh: 'readonly',
  usePilotFlags: 'readonly',
  useSmsCapability: 'readonly',
  useSwipePager: 'readonly',
  $fetch: 'readonly',
  provide: 'readonly',
  inject: 'readonly',
  resolveComponent: 'readonly',
  resolveDirective: 'readonly',
  useAttrs: 'readonly',
  useSlots: 'readonly',
  useId: 'readonly',
  useModel: 'readonly',
  useTemplateRef: 'readonly',
  defineAsyncComponent: 'readonly',
  defineOptions: 'readonly',
  defineModel: 'readonly',
  shallowRef: 'readonly',
  shallowReactive: 'readonly',
  toRef: 'readonly',
  toRefs: 'readonly',
  unref: 'readonly',
  isRef: 'readonly',
  isReactive: 'readonly',
  isReadonly: 'readonly',
  markRaw: 'readonly',
  effectScope: 'readonly',
  getCurrentInstance: 'readonly',
  onBeforeMount: 'readonly',
  onBeforeUpdate: 'readonly',
  onUpdated: 'readonly',
  onActivated: 'readonly',
  onDeactivated: 'readonly',
  onErrorCaptured: 'readonly',
  onServerPrefetch: 'readonly',
  useCssModule: 'readonly',
  useCssVars: 'readonly',
  useShadowRoot: 'readonly',
  useError: 'readonly',
  clearNuxtData: 'readonly',
  refreshNuxtData: 'readonly',
  reloadNuxtApp: 'readonly',
  abortNavigation: 'readonly',
  addRouteMiddleware: 'readonly',
  useRequestEvent: 'readonly',
  useAppConfig: 'readonly',
  useDevice: 'readonly',
  useColorMode: 'readonly',
  useToast: 'readonly',
}

export default [
  {
    ignores: [
      '.output/**',
      '.nuxt/**',
      'node_modules/**',
      'coverage/**',
      'dist/**',
      'scripts/**',
      '**/*.{ts,tsx}',
      '**/*.d.ts',
    ],
  },
  js.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  ...vueA11y.configs['flat/recommended'],
  {
    files: ['**/*.{js,mjs,vue}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...nuxtGlobals,
      },
      parser: vueParser,
      parserOptions: {
        parser: tsParser,
        ecmaVersion: 'latest',
        sourceType: 'module',
        extraFileExtensions: ['.vue'],
      },
    },
    rules: {
      'vuejs-accessibility/label-has-for': 'warn',
      'vuejs-accessibility/click-events-have-key-events': 'warn',
      'vuejs-accessibility/form-control-has-label': 'warn',
      'no-unused-vars': 'off',
      // Style noise — not production blockers; keep a11y/security signal.
      'vue/multi-word-component-names': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-indent': 'off',
      'vue/html-self-closing': 'off',
      'vue/attributes-order': 'off',
      'vue/first-attribute-linebreak': 'off',
    },
  },
]
